### ISSUE TITLE
WORKDIR should allow env variables

### ISSUE THREAD

**Issue by gudleik** [RedCoolBeans/dockerlint#17] opened 2016-09-19 12:51 UTC
### Issue details

Using an environment variable as WORKDIR should be allowed.
### Steps to reproduce/test case

This is valid syntax in a Dockerfile:

``` Dockerfile
ENV MY_PATH=/var/foo
WORKDIR $MY_PATH
```

But dockerlint says `WORKDIR path $MY_PATH must be absolute`.
### Affected version(s)
- linter-docker v0.1.2

**Comment by SharpEdgeMarshall** [comment] 2016-10-04 08:25
Duplicate of #9

**Closed** 2017-04-02 13:26 UTC
